# Generated by Django 5.1.2 on 2026-03-24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("event_date", models.DateTimeField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("LECTURE", "Lecture"),
                            ("HACKATHON", "Hackathon"),
                            ("FORUM", "Forum"),
                            ("VOLUNTEER", "Volunteer"),
                            ("OTHER", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("difficulty_coef", models.DecimalField(decimal_places=2, default=Decimal("1.00"), max_digits=4)),
                ("base_points", models.PositiveIntegerField(default=0)),
                ("max_participants", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ONGOING", "Ongoing"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="events", to="events.eventcategory"),
                ),
                (
                    "organizer",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="organized_events", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={"ordering": ("-event_date",)},
        ),
        migrations.CreateModel(
            name="Prize",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "prize_type",
                    models.CharField(
                        choices=[
                            ("MERCH", "Merch"),
                            ("TICKETS", "Tickets"),
                            ("INTERNSHIP", "Internship"),
                            ("GRANT", "Grant"),
                            ("MEETING", "Meeting"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="prizes", to="events.event")),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="Participation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REGISTERED", "Registered"),
                            ("CHECKED_IN", "Checked In"),
                            ("CONFIRMED", "Confirmed"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="REGISTERED",
                        max_length=16,
                    ),
                ),
                ("qr_token", models.CharField(max_length=128, unique=True)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("points_awarded", models.PositiveIntegerField(default=0)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="participations", to="events.event")),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="event_participations", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddConstraint(
            model_name="participation",
            constraint=models.UniqueConstraint(fields=("event", "user"), name="unique_event_user_participation"),
        ),
    ]
