# Generated by Django 5.2.12 on 2026-03-24 13:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-event_date',), 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'ordering': ('name',), 'verbose_name': 'Категория мероприятия', 'verbose_name_plural': 'Категории мероприятий'},
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventcategory'),
        ),
        migrations.AlterField(
            model_name='event',
            name='difficulty_coef',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('LECTURE', 'Лекция'), ('HACKATHON', 'Хакатон'), ('FORUM', 'Форум'), ('VOLUNTEER', 'Волонтёрство'), ('OTHER', 'Другое')], max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, default=100, null=True),
        ),
    ]
