# Generated by Django 5.2.12 on 2026-03-24 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_it', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rating_social', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rating_media', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('common_rating', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('snapshot_date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Снимок рейтинга',
                'verbose_name_plural': 'Снимки рейтинга',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='PointWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LECTURE', 'Лекция'), ('HACKATHON', 'Хакатон'), ('FORUM', 'Форум'), ('VOLUNTEER', 'Волонтёрство')], max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventcategory')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Вес баллов',
                'verbose_name_plural': 'Веса баллов',
                'unique_together': {('event_type', 'category')},
            },
        ),
    ]
